-- Your SQL goes here
CREATE TABLE posts(
  id   		 SERIAL PRIMARY KEY,
  user_id 	 SERIAL NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  created_on TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_on TIMESTAMP NOT NULL DEFAULT NOW(),
  body 	 	 VARCHAR(255) NOT NULL,
  up_votes   INTEGER NOT NULL DEFAULT 0,
  down_votes INTEGER NOT NULL DEFAULT 0
)
